export const employees = [
  {
    id: 1,
    firstName: "Arjun",
    email: "e@e.com",
    password: "123",
    taskCounts: {
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        id: 101,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Update website",
        taskDescription: "Revamp the homepage design",
        taskDate: "2024-10-12",
        category: "Design",
      },
      {
        id: 102,
        active: false,
        completed: false,
        failed: false,
        taskTitle: "Client meeting",
        taskDescription: "Discuss project requirements",
        taskDate: "2024-10-10",
        category: "Meeting",
      },
      {
        id: 103,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Fix bugs",
        taskDescription: "Resolve bugs reported in issue tracker",
        taskDate: "2024-10-14",
        category: "Development",
      },
    ],
  },
  {
    id: 2,
    firstName: "Sneha",
    email: "employee2@example.com",
    password: "123",
    taskCounts: {
      newTask: 0,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        id: 201,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Database optimization",
        taskDescription: "Optimize queries for better performance",
        taskDate: "2024-10-11",
        category: "Database",
      },
      {
        id: 202,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Design new feature",
        taskDescription: "Create mockups for the new feature",
        taskDate: "2024-10-09",
        category: "Design",
      },
    ],
  },
  {
    id: 3,
    firstName: "Ravi",
    email: "employee3@example.com",
    password: "123",
    taskCounts: {
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        id: 301,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare presentation",
        taskDescription: "Prepare slides for upcoming client presentation",
        taskDate: "2024-10-13",
        category: "Presentation",
      },
      {
        id: 302,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Code review",
        taskDescription: "Review the codebase for optimization",
        taskDate: "2024-10-12",
        category: "Development",
      },
      {
        id: 303,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Testing",
        taskDescription: "Test the latest build for bugs",
        taskDate: "2024-10-08",
        category: "QA",
      },
    ],
  },
  {
    id: 4,
    firstName: "Priya",
    email: "employee4@example.com",
    password: "123",
    taskCounts: {
      newTask: 1,
      completed: 0,
      failed: 0,
    },
    tasks: [
      {
        id: 401,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Write documentation",
        taskDescription: "Update the project documentation",
        taskDate: "2024-10-13",
        category: "Documentation",
      },
      {
        id: 402,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Set up CI/CD",
        taskDescription: "Implement continuous integration pipeline",
        taskDate: "2024-10-11",
        category: "DevOps",
      },
    ],
  },
  {
    id: 5,
    firstName: "Karan",
    email: "emp005@example.com",
    password: "123",
    taskCounts: {
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        id: 501,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "UI redesign",
        taskDescription: "Redesign the user interface for better UX",
        taskDate: "2024-10-14",
        category: "Design",
      },
      {
        id: 502,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "UI redesign",
        taskDescription: "Redesign the user interface for better UX",
        taskDate: "2024-10-14",
        category: "Design",
      },
      {
        id: 503,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Deploy new build",
        taskDescription: "Deploy the latest build to production",
        taskDate: "2024-10-09",
        category: "DevOps",
      },
      {
        id: 504,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Client feedback",
        taskDescription: "Gather feedback from clients after product launch",
        taskDate: "2024-10-12",
        category: "Support",
      },
    ],
  },
];


export const admins = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
    firstName: "Akash Nath",
  },
  {
    id: 2,
    email: "admin2@example.com",
    password: "123",
    firstName: "Debabrata Nath",
  },
];
