export const Users = [
  {
    uid: "hmDPUAhUroWzKf23NV0ll40cRPg2",
    firstName: "Arjun",
    email: "e@e.com",
    password: "123456",
    role: "employee",
    tasks: [
      {
        id: 1,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Daily Sales Report",
        taskDescription: "Compile and submit daily sales data.",
        taskDate: "2023-09-30",
        category: "Reporting",
      },
      {
        id: 2,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Product Training Session",
        taskDescription: "Attend training for new product line.",
        taskDate: "2023-10-05",
        category: "Training",
      },
    ],
  },
  {
    uid: "dMC5eHv0azTfKVq5yNIHOMuFIoQ2",
    firstName: "Sneha",
    email: "employee2@example.com",
    password: "123456",
    role: "employee",
    tasks: [
      {
        id: 3,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Client Meeting",
        taskDescription: "Meet with client to discuss project requirements.",
        taskDate: "2023-10-01",
        category: "Meetings",
      },
    ],
  },
  {
    uid: "2ZvupdAuSBeIGhQXewwv13yIFwB2",
    firstName: "Ravi",
    email: "employee3@example.com",
    password: "123456",
    role: "employee",
    tasks: [
      {
        id: 4,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Market Research",
        taskDescription: "Conduct research on market trends.",
        taskDate: "2023-10-03",
        category: "Research",
      },
      {
        id: 5,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Team Meeting",
        taskDescription: "Weekly team sync-up meeting.",
        taskDate: "2023-09-28",
        category: "Meetings",
      },
    ],
  },
  {
    uid: "ZRZFgRMoNmZEBi7RxaKcP29D5H03",
    firstName: "Priya",
    email: "employee4@example.com",
    password: "123456",
    role: "employee",
    tasks: [
      {
        id: 6,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Prepare Presentation",
        taskDescription: "Create presentation for Monday's meeting.",
        taskDate: "2023-10-02",
        category: "Documentation",
      },
    ],
  },
  {
    uid: "H7iIsdsLTrerUVNNklcNHGg9bRr2",
    firstName: "Arian",
    email: "emp006@example.com",
    password: "123456",
    role: "employee",
    tasks: [
      {
        id: 9,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Website Content Update",
        taskDescription: "Update homepage banners and product info.",
        taskDate: "2023-10-06",
        category: "Development",
      },
      {
        id: 10,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Internal Audit",
        taskDescription: "Assist in internal process audit.",
        taskDate: "2023-09-27",
        category: "Audit",
      },
    ],
  },
  {
    uid: "DVJhcBZmb5YVVlJ7feLoghxuMje2",
    firstName: "Arnob",
    email: "emp007@example.com",
    password: "123456",
    role: "employee",
    tasks: [
      {
        id: 11,
        active: true,
        completed: false,
        failed: false,
        taskTitle: "Software Testing",
        taskDescription: "Test the new CRM features before release.",
        taskDate: "2023-10-07",
        category: "QA",
      },
      {
        id: 12,
        active: false,
        completed: true,
        failed: false,
        taskTitle: "Documentation",
        taskDescription: "Update user manuals for software release.",
        taskDate: "2023-09-26",
        category: "Documentation",
      },
    ],
  },
  {
    uid: "N3I1GLucJpOONeTGswjJ3Cwo2SD3",
    email: "admin@example.com",
    password: "123456",
    firstName: "Akash Nath",
    role: "admin",
  },
  {
    uid: "QwHmnbZKRxb7srmQUxxr4ByhzNA2",
    email: "admin2@example.com",
    password: "123456",
    firstName: "Debabrata Nath",
    role: "admin",
  },
];
